[package]
name = "bdk-cli"
version = "0.1.0"
edition = "2018"
authors = ["Alekos Filini <alekos.filini@gmail.com>", "Riccardo Casatta <riccardo@casatta.it>"]

[dependencies]
bdk = { git = "https://github.com/bitcoindevkit/bdk.git" }
bdk-macros = { git = "https://github.com/bitcoindevkit/bdk.git" }
structopt = "^0.3"
serde_json = { version = "^1.0" }
log = "^0.4"
base64 = "^0.11"

# Optional dependencies
async-trait = { version = "0.1", optional = true }
rustyline = { version = "6.0", optional = true }
dirs-next = { version = "2.0", optional = true }
env_logger = { version = "0.7", optional = true }
clap = { version = "2.33", optional = true }

[features]
default = ["repl", "esplora"]
repl = ["async-trait", "rustyline", "dirs-next", "env_logger", "clap", "electrum"]
electrum = ["bdk/electrum"]
esplora = ["bdk/esplora"]


[[bin]]
name = "repl"
path = "src/repl.rs"
required-features = ["repl"]