on: [push]

name: Code Coverage

jobs:
  tarpaulin-codecov:
    name: Tarpaulin to codecov.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set default toolchain
        run: rustup default nightly
      - name: Set profile
        run: rustup set profile minimal

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Tarpaulin
        run: cargo tarpaulin --features default --run-types Tests,Doctests --out Xml

      - name: Publish to codecov.io
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
          file: ./cobertura.xml
